### ISSUE TITLE
Realmのデーターを加工してグラフに表示する

### ISSUE THREAD

**Issue by aoba320** [lit-monster/Calendar#45]

**Comment by MasakazOzaki** [comment]
最高優先度．
春キャンプで必ず終わらせる．

**Comment by MasakazOzaki** [comment]
- 保存自体はできている
<img width="681" alt="Screen Shot 2022-04-03 at 1 28 21" src="https://user-images.githubusercontent.com/15528096/161392211-f4e5d3d8-bed5-4c0f-a8c0-e995e3c3b375.png">

あとはこれを加工して，rawDataに持っていきたい．

## STEP1
- 日付ごと，週ごと，月ごと，年ごとのsegentedControlのdidChangeをひろう


## STEP2 これが一番大変
![IMG_5435 copy](https://user-images.githubusercontent.com/15528096/161392527-a08542e6-2eab-4942-b8b8-d361aeb6c668.png)
- データを
```
[[A,B,C], [D,E,F], [G,H,I], [J, K, L], [M, N, O], [P, Q, R], [S, T, U]]
```
の値の二次元配列に加工するよ．このデータさえできてしまえば勝手にグラフになる．
欲しいデータの数分，配列がデカくなるからいい感じにがんばろうな．

欲しい範囲の全データを取得してStudyQualityごとに足して行って配列にappendするという結構難しいプログラムを書く必要があるぜよ．一緒にやろう．一緒にやれば1.5hぐらいでできると思う．(多分)

**Comment by MasakazOzaki** [comment]
@aoba320 
- 保存自体はできている
<img width="681" alt="Screen Shot 2022-04-03 at 1 28 21" src="https://user-images.githubusercontent.com/15528096/161392211-f4e5d3d8-bed5-4c0f-a8c0-e995e3c3b375.png">

あとはこれを加工して，rawDataに持っていきたい．

## STEP1
- 日付ごと，週ごと，月ごと，年ごとのsegentedControlのdidChangeをひろう


## STEP2 これが一番大変
![IMG_5435 copy](https://user-images.githubusercontent.com/15528096/161392527-a08542e6-2eab-4942-b8b8-d361aeb6c668.png)
- データを
```
[[A,B,C], [D,E,F], [G,H,I], [J, K, L], [M, N, O], [P, Q, R], [S, T, U]]
```
の値の二次元配列に加工するよ．このデータさえできてしまえば勝手にグラフになる．
欲しいデータの数分，配列がデカくなるからいい感じにがんばろうな．

欲しい範囲の全データを取得してStudyQualityごとに足して行って配列にappendするという結構難しいプログラムを書く必要があるぜよ．一緒にやろう．一緒にやれば1.5hぐらいでできると思う．(多分)
