### ISSUE TITLE
UI実装

### ISSUE THREAD

**Issue by masakazozaki** [lit-monster/Calendar#50]
実装しようこれ

<img width="288" alt="Screen Shot 2022-04-01 at 0 34 24" src="https://user-images.githubusercontent.com/15528096/161093698-71c007fd-37a9-406d-a78e-413e026c7706.png">

**Comment by MasakazOzaki** [comment]
@aoba320 
CollectionViewで実装する
結構重いのでCollectionView復習しとくといいかも．TableViewとほぼ同じだけど教科書にないので，教科書のTechPodでtableview復習しとこう
